apiVersion: apps/v1
kind: Deployment
metadata:
  name: pschatbot
  namespace: pschatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pschatbot
  template:
    metadata:
      labels:
        app: pschatbot
    spec:
      containers:
      - name: pschatbot
        image: docker.io/avasil08/ps-chatbot:acc.1.0.4
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: "development"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: pschatbot-pvc
            mountPath: /app/docs

      volumes:
        - name: pschatbot-pvc
          persistentVolumeClaim:
            claimName: pschatbot-pvc

      imagePullSecrets:
      - name: regcred