apiVersion: apps/v1
kind: Deployment
metadata:
  name: pschatbot-deployment
  namespace: pschatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pschatbot
  template:
    metadata:
      labels:
        app: pschatbot
    spec:
      containers:
      - name: pschatbot
        image: docker.io/avasil08/ps-chatbot:acc.1.0.0
        env:
        - name: FLASK_ENV
          value: "development"
        ports:
        - containerPort: 5000