apiVersion: v1
kind: Service
metadata:
  name: pschatbot-service
  namespace: pschatbot
spec:
  type: ClusterIP
  selector:
    app: pschatbot
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000