name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: avasil08
        password: dckr_pat_9vP5dVWomAugJGg_lc-FedkwA9M

    - name: Extract short SHA
      id: short-sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/avasil08/ps-chatbot:${{ env.SHORT_SHA }}

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: docker.io/avasil08/ps-chatbot:.*|image: docker.io/avasil08/ps-chatbot:${{ env.SHORT_SHA }}|" ./manifests/pschatbot-deployment.yaml

    - name: Commit and push changes
      run: |
        git add ./manifests/pschatbot-deployment.yaml
        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
        git push https://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@github.com/${{ github.repository }} HEAD:main