name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/avasil08/ps-chatbot:${{ github.sha }}

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: docker.io/avasil08/ps-chatbot:.*|image: docker.io/avasil08/ps-chatbot:${{ github.sha }}|" ./manifests/pschatbot-deployment.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./manifests/pschatbot-deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push